In [1]:
# Title: API Data Collection and Processing using Python

# Description:
# This project focuses on collecting data from APIs using Python, processing the 
# response data, and preparing it for analysis.

# Tools Used: Python, Requests, Pandas, Jupyter Notebook
!pip install requests

Requirement already satisfied: requests in c:\users\91917\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\91917\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91917\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\91917\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91917\anaconda3\lib\site-packages (from requests) (2025.11.12)

In [1]:
import requests

In [2]:
url="https://stephen-king-api.onrender.com/api/books"
res=requests.get(url)

In [ ]:
data=res.json()
data

In [10]:
import pandas as pd

In [19]:
df=pd.json_normalize(data["data"])
df.columns
df=df[["Year","Title","Publisher"]]
df

    Year          Title        Publisher
0   1974         Carrie        Doubleday
1   1975    Salem's Lot        Doubleday
2   1977    The Shining        Doubleday
3   1977           Rage     Signet Books
4   1978      The Stand        Doubleday
..   ...            ...              ...
58  2018   The Outsider         Scribner
59  2018      Elevation         Scribner
60  2019  The Institute         Scribner
61  2021          Later  Hard Case Crime
62  2021  Billy Summers         Scribner

[63 rows x 3 columns]

In [22]:
link="https://api.weather.gov/openapi.json"
res=requests.get(link)
res

In [26]:
info=res.json()
df1=pd.json_normalize(info)

In [28]:
df1[["servers","info.title"]]

                                             servers       info.title
0  [{'url': 'https://api.weather.gov', 'descripti...  weather.gov API

In [ ]:
# Key Learnings:

# Working with APIs and HTTP requests

# Handling JSON data

# Data extraction and processing using Python

# Real-world data collection techniques